### ISSUE TITLE
YouTube has slow loading time, when using FX container and "always open this site in..." option

### ISSUE THREAD

**Issue by krisu5** [polcak/jsrestrictor#187]
## Summary

When using [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) (from now on, I'm just gonna use "MAC" abbreviation) and JShelter together **with** MAC's "always open this site in..." setting setup for some container on YouTube.com, site's loading times significally slow down.

It doesn't even start to render the page until after ~10 sec.

The MAC's "always open this site in..." setting setup is important in here, because when manually adding the container to YouTube, load time is acceptable.

Also opening YouTube without container loads fine.

## Setup

Pages affected: https://www.youtube.com
JShelter Version: 0.11

Popup information (open JShelter popup on affected pages:

_Setup info made with clean portable Firefox setup with minimal amount of addons (more info at "Reproducibility" section)_

1. Navigate to a page that you are having trouble with: **https://www.youtube.com & https://www.youtube.com/feed/subscriptions**
2. Click on the JShelter badge icon.
3. Is JavaScript Shield active? **ON and OFF, both having same result.**
3. Is Network Boundary Shield active? **ON and OFF, both having same result.**
3. Is Fingerprint Detector active? **ON and OFF, both having same result.**
4. What fingerprint likelihood does Fingerprint Detector report? **[fpd_report_www.youtube.com.json.txt](https://github.com/polcak/jsrestrictor/files/8695294/fpd_report_www.youtube.com.json.txt)**
5. Did Fingerprint Detector produce any notifications, if so, what was the notification? **No**
6. Click on the `Modify` button next to the JavaScript Shield label.
7. What is the highlighted level button text? **Default level (recommended)**
8. Click on the `Detail tweaks of JS shield for this site` button.
9. What wrappers were triggered by the page, list them below:
- Time precision (1000 or more)
- Idle period (50 and adding up over time)
- Installed browser plugins (3)
- Device memory and CPU (3)
- Connected cameras and microphones (2)

[Optional:]

OS: Windows 10 Pro
Browser: Firefox 100.0
Other extensions that might affect JShelter behaviour: [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) 

## How to reproduce

1. Install [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)
2. Go to https://youtube.com
3. Click MAC extension icon
4. Click "Always open this site in..."
5. Select any container (eg. `Personal`)

## Expected result

Acceptable and close to normal load times (2-4 secs)

## Actual result

~10 seconds of added load time + normal load time

## Reproducibility

I have tested this with my personal Firefox setup and seperate clean portable Firefox setup with only added changes were installed addons (uBlock Origin, MAC, JShelter).

## Workarounds

1. Click MAC extension icon
2. Click "Manage containers"
3. Select the container that effects YouTube
4. Click "Manage site list"
5. Remove "www.youtube.com"
6. Use YouTube without container or manually added container.

**Comment by brochard** [comment]
Can confirm I have the same very very slow loading when I open any containered site (tested youtube, google, twitch, amazon, facebook, netflix...)

**Comment by polcak** [comment]
I tested current MAC with 0.11, 0.12.2, and 0.15.2. The load time was about 3-4 seconds on my computer with each version and also without MAC. Maybe it was an issue in MAC that was fixed in the mean time?

**Comment by polcak** [comment]
I was using Firefox 118 beta. Maybe the issue was in Firefox?

**Comment by brochard** [comment]
I tried again on both Firefox 117 and 119 and I still have this issue
